### PR TITLE
[ZEN-4200] Support new configuration options in Swagger-UI v3 GenTemplate

### PR DESCRIPTION
**Pull request by ghillairet**
PR taken from https://github.com/ModelSolv/RepreZen/pull/1759/files and ported to GenFlow.

### CODE REVIEW

**Comment by tedepstein** [comment]
Needs to be tested in [API Studio PR #1865](https://github.com/ModelSolv/RepreZen/pull/1865).

**Comment by tedepstein** [comment]
Wait until we merge #55, addressing version ranges and dependency partitioning, then do any needed refactoring in this PR before we merge this one.

**Comment by ghillairet** [comment]
@nbhusare See https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

**Comment by tedepstein** [comment]
@nbhusare , for our testing, we should refer to the  SUI documentation here: 
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

**Comment by nbhusare** [comment]
Passed QA

**Comment by tedepstein** [comment]
@neerajbhusare , please set the versions back to a standard SNAPSHOT as per the usual process, and merge this PR. You can also similarly update the corresponding https://github.com/RepreZen/GenFlow/pull/50 PR and merge that one.

**Comment by tedepstein** [comment]
@neerajbhusare , I just corrected my comment from above:

> ...You can also similarly update the corresponding ~https://github.com/RepreZen/GenFlow/pull/50~ https://github.com/ModelSolv/RepreZen/pull/1865 PR and merge that one.

**Pull request merged**
