### PR TITLE
[ZEN-4707] GenFlow: Upgrade to SCG 2.4.4 to address SCG Kotlin Server codegen failure

### PR DESCRIPTION
**Pull request by ghillairet**
@tedepstein Could be part of new GenFlow release, also would allow to merge https://github.com/RepreZen/GenFlow/pull/54 and fix issue with some generators see https://modelsolv.atlassian.net/browse/ZEN-4707

Not sure if there is anything to change in the generated csv files.

### CODE REVIEW

**Comment by tedepstein** [comment]
@ghillairet ,  the last build was still resolving to Swagger-Codegen 2.4.0, as described in the comment from Neeraj [here](https://modelsolv.atlassian.net/browse/ZEN-4707?focusedCommentId=45958&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-45958).  

Is your most recent commit intended to fix this?

**Comment by ghillairet** [comment]
@tedepstein It does aligned other swagger dependencies to codeine 2.4.4 and also here https://github.com/ModelSolv/RepreZen/pull/1884 I fixed swagger dependencies in the bundles.

**Comment by tedepstein** [comment]
@tedepstein to review and (if needed) update the new CSV Metadata, describing changes in the available codegen modules & parameters.

**Comment by tedepstein** [comment]
@ghillairet , @neerajbhusare , I've reviewed the metadata, and in fact there are no changes from 2.40 to 2.4.4.  No new, delete, or modified generator modules or parameters. I guess that's to be expected. 

As noted in [Neeraj's comment](https://modelsolv.atlassian.net/browse/ZEN-4707?focusedCommentId=45971&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-45971) on the Jira issue, this has passed QA. The Kotlin generator should work now. 

So I'll merge this now, along with the corresponding API Studio PR.

**Comment by ghillairet** [comment]
@tedepstein Those changes have been lost during the merges.

**Comment by ghillairet** [comment]
Only the swagger-codegen version was missing, I put it back here https://github.com/RepreZen/GenFlow/commit/a5e5c960b1b3ce96ff87e1b1718ae57a44e94606

**Comment by tedepstein** [comment]
Thanks, @ghillairet

**Pull request merged**
