### PR TITLE
Task/zen 4408 Improve SCG and OAG implementations and upgrade processes

### PR DESCRIPTION
**Pull request by andylowry**
Much of the logic in SCG and OAG implementations has now been refactored into common classes appearing in the `common` project. The classes remaining in `swagger-codegen` and `openapi-generator` projects are significantly simplified by deriving from these classes.

In addition, the update process has been improved significantly:
* Instead of a single pair of csv files representing the current module information, there is now a pair of files for each version of the underlying libraries (`swagger-codegen` or `openapi-generator`) that has been configured for a build. When GenFlow is built with a new version of either library, a new pair of info files is created in the corresponding project(s), with info for the prior version carried forward automatically.
* If module info files exist for a given library version, those files are not re-written during a build, but they may be edited manually.
* Modules have new boolean properties:
  * *New* means the module did not appear in the prior version's module info, but does appear in this one.
  * *Deleted* means the module appeared in the prior version's module info, but does not appear in this version.
 * *Vetted* is never set by the discovery process for new modules, but it is preserved for modules carried forward from the prior version. Unvetted modules are not active in API Studio.

So the typical process for upgrading now is:
* Change the version for one or both libraries in the GenFlow root-level pom file
* Perform a build of GenFlow
* Edit the new CSV file(s), setting Vetted and/or Suppressed flags, as well as DisplayName values to override the automatic DerivedName values.
* Save the CSV file and re-build.

The edit/rebuild process can occur over multiple commits, and across releases, without any difficulty.

### CODE REVIEW

**Comment by andylowry** [comment]
@tedepstein I've reworked the SCG and OAG implementations considerably, including making the process of managing suppressions and name overrides considerably more robust. Take a look at this PR description for an overview, and let me know what you think.

I'm going to perform a snapshot build with this branch in its current state (same versions of SCG and OAG libraries as we currently use). Then I'll add a commit bumping the versions to the current latest releases, and the result will be new CSV files for those releases. I'll leave the project in that state, which will give you the opportunity to see the spreadsheets in their pre-edited form and take a stab at editing them.

**Comment by andylowry** [comment]
@tedepstein I've just pushed GenFlow changes that bump our SCG and OAG versions to 2.4.0 and 3.3.4, respectively. The spreadsheets with the module metadata are in
* `modules/gentemplates/swagger-codgen/src/main/resources/com/reprezen/swagger/codegen` for SCG
* `modules/gentemplates/openapi-generator/src/main/resources/com/reprezen/openapi/generator` for OAG.

In each case you'll find `modulesInfo_<version>.csv` and `moduleParams_<version>.csv`. There's generally no need to edit the `moduleParams` file, just the `modulesInfo` file. Mostly what's needed is adding names in the `DisplayName` column where the values in the `DerivedName` column are not satisfactory.

Note that the `New` column flags are not working correctly. I'll fix that, but for now if you just focus on the `Vetted` column, the ones with out stars are the new modules. (The rest had all been vetted in the CSV files for the prior releases, and those Vetted flags were carried forward).

**Comment by tedepstein** [comment]
Looks great, @andylowry. I’ll take a closer look as soon as I get a chance. But it sounds like a much more manageable process that will allow us to keep things up to date much more easily.

**Comment by andylowry** [comment]
@tedepstein I've fixed the logic for the New and Changed statuses and re-built the CSV files for SCG v2.4.0 and OAG v3.3.4.

Meanings of flags are:
* Suppressed - never set in discovery, manually set in order to prevent a module from being adapted as a GenTemplate at runtime
* Changed - set during discovery when any of the tracked info about a module has changed since the prior version (type, reported name, derived display name); also set whenever New or Deleted is set
* Deleted - set during discovery when a module present in the prior version is no longer present (deleted modules are carried only one version forward)
* New - set during discovery when module is present in the current version but not in the prior version
* Vetted - never set in discovery, manually set in order to enable a module to be adapted as a GenTemplate

**Comment by andylowry** [comment]
@ghillairet This is ready for review.

**Pull request merged**
